Remove references to korn.
CATechnologiesTest/yipee pull request #46
Opened 2018-12-18 18:46 UTC by andrewcopley

2018-12-21 19:15 UTC, jd3quist approved these changes
A couple nitpicks on test file data.

Assuming you fix those, LGTM

2018-12-21 19:15 UTC, jd3quist commented on ui/src/app/models/YipeeFileMetadataRaw.spec.ts
> +          'image': 'yipee-tools-spoke-cos.ca.com:5000',
I assume this is a test-data file?  The image name that you have here now is not a valid docker image name.  It has only the "registry" part but no actual image name.  Since we're docker guys I think we should use (structurally) valid image names.

I don't think it would hurt to leave "korn" there like it was.  But if you're going for string letter-of-the-law on removing "korn" let's make it be "foo" here.  That is at least a valid image name.  You wouldn't be able to resolve it of course, but that's OK.

yipee-tools-spoke-cos.ca.com:5000/foo

2018-12-21 19:15 UTC, jd3quist commented on ui/src/app/models/YipeeFileMetadataRaw.spec.ts
> +          'image': 'yipee-tools-spoke-cos.ca.com:5000',
same comment as above

2018-12-21 19:15 UTC, jd3quist commented on ui/src/app/shared/services/yipee-file.service.spec.ts
> +        'image': 'yipee-tools-spoke-cos.ca.com:5000',
same comment as above

2018-12-21 19:19 UTC, D3nn approved these changes
Aside from the comments that @jd3quist made about the image names, everything else LGTM.

2018-12-26 17:19 UTC, bl8nr approved these changes

2018-12-27 17:03 UTC, markemeis requested changes
Once Jim's comments are addressed I'm good with this.

2019-01-02 19:15 UTC, andrewcopley commented on ui/src/app/models/YipeeFileMetadataRaw.spec.ts
> +          'image': 'yipee-tools-spoke-cos.ca.com:5000',
Changed to foo.

2019-01-02 19:15 UTC, andrewcopley commented on ui/src/app/shared/services/yipee-file.service.spec.ts
> +        'image': 'yipee-tools-spoke-cos.ca.com:5000',
Changed to foo.

2019-01-02 19:15 UTC, andrewcopley commented on ui/src/app/models/YipeeFileMetadataRaw.spec.ts
> +          'image': 'yipee-tools-spoke-cos.ca.com:5000',
Changed to foo.

2019-01-02 19:16 UTC, merged